#
# Copyright 2024 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Description:
#
#   This template defines a stages-based pipeline for building N3xx FPGA targets.
#
#   See https://aka.ms/yaml for pipeline YAML documentation.
#

parameters:
## Optional parameters
# Option to ignore cached artifacts (if available) and perform
# a clean IP build.
- name: clean_ip_build
  type: boolean
  default: false
# Number of parallel jobs to use for IP build
- name: num_ip_jobs
  type: number
  default: 5
# Option to publish intermediate files
- name: publish_int_files
  type: boolean
  default: false
# Package and publish images
- name: package_and_publish_images
  type: boolean
  default: true
# Package access in the SDR server ('Internal' or 'Public')
- name: package_access
  type: string
  default: 'Internal'
# From where to pull FPGA bitfiles if we're not building them
- name: fpga_imgs_source
  type: string
  default: 'Mono Pipeline'
# N300 FPGA targets to build
- name: n300_full_targets_matrix
  type: object
  default:
    N300_HG:
      image_core: n300_rfnoc_image_core.yml
      target_name: N300_HG
      artifact_name: N300_HG
      image_core_name: usrp_n300_fpga_HG
      timeout: 720
      max_attempts: 2
    N300_XG:
      image_core: n300_rfnoc_image_core.yml
      target_name: N300_XG
      artifact_name: N300_XG
      image_core_name: usrp_n300_fpga_XG
      timeout: 720
      max_attempts: 2
    N300_WX:
      image_core: n300_rfnoc_image_core.yml
      target_name: N300_WX
      artifact_name: N300_WX
      image_core_name: usrp_n300_fpga_WX
      timeout: 720
      max_attempts: 2
    N300_AA:
      image_core: n300_bist_rfnoc_image_core.yml
      target_name: N300_AA
      artifact_name: N300_AA
      image_core_name: usrp_n300_fpga_AA
      timeout: 720
      max_attempts: 2
- name: n300_reduced_targets_matrix
  type: object
  default:
    N300_HG:
      image_core: n300_rfnoc_image_core.yml
      target_name: N300_HG
      artifact_name: N300_HG
      image_core_name: usrp_n300_fpga_HG
      timeout: 720
      max_attempts: 2
# N310 FPGA targets to build
- name: n310_full_targets_matrix
  type: object
  default:
    N310_HG:
      image_core: n310_rfnoc_image_core.yml
      target_name: N310_HG
      artifact_name: N310_HG
      image_core_name: usrp_n310_fpga_HG
      timeout: 720
      max_attempts: 2
    N310_XG:
      image_core: n310_rfnoc_image_core.yml
      target_name: N310_XG
      artifact_name: N310_XG
      image_core_name: usrp_n310_fpga_XG
      timeout: 720
      max_attempts: 2
    N310_WX:
      image_core: n310_rfnoc_image_core.yml
      target_name: N310_WX
      artifact_name: N310_WX
      image_core_name: usrp_n310_fpga_WX
      timeout: 720
      max_attempts: 2
    N310_AA:
      image_core: n310_bist_rfnoc_image_core.yml
      target_name: N310_AA
      artifact_name: N310_AA
      image_core_name: usrp_n310_fpga_AA
      timeout: 720
      max_attempts: 2
- name: n310_reduced_targets_matrix
  type: object
  default:
    N310_HG:
      image_core: n310_rfnoc_image_core.yml
      target_name: N310_HG
      artifact_name: N310_HG
      image_core_name: usrp_n310_fpga_HG
      timeout: 720
      max_attempts: 2
    N310_XG:
      image_core: n310_rfnoc_image_core.yml
      target_name: N310_XG
      artifact_name: N310_XG
      image_core_name: usrp_n310_fpga_XG
      timeout: 720
      max_attempts: 2
# N320 FPGA targets to build
- name: n320_full_targets_matrix
  type: object
  default:
    N320_HG:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_HG
      artifact_name: N320_HG
      image_core_name: usrp_n320_fpga_HG
      timeout: 720
      max_attempts: 2
    N320_XG:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_XG
      artifact_name: N320_XG
      image_core_name: usrp_n320_fpga_XG
      timeout: 720
      max_attempts: 2
    N320_WX:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_WX
      artifact_name: N320_WX
      image_core_name: usrp_n320_fpga_WX
      timeout: 720
      max_attempts: 2
    N320_AA:
      image_core: n320_bist_rfnoc_image_core.yml
      target_name: N320_AA
      artifact_name: N320_AA
      image_core_name: usrp_n320_fpga_AA
      timeout: 720
      max_attempts: 2
    N320_AQ:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_AQ
      artifact_name: N320_AQ
      image_core_name: usrp_n320_fpga_AQ
      timeout: 720
      max_attempts: 2
    N320_XQ:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_XQ
      artifact_name: N320_XQ
      image_core_name: usrp_n320_fpga_XQ
      timeout: 720
      max_attempts: 2
- name: n320_reduced_targets_matrix
  type: object
  default:
    N320_HG:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_HG
      artifact_name: N320_HG
      image_core_name: usrp_n320_fpga_HG
      timeout: 720
      max_attempts: 2
    N320_XG:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_XG
      artifact_name: N320_XG
      image_core_name: usrp_n320_fpga_XG
      timeout: 720
      max_attempts: 2
    N320_XQ:
      image_core: n320_rfnoc_image_core.yml
      target_name: N320_XQ
      artifact_name: N320_XQ
      image_core_name: usrp_n320_fpga_XQ
      timeout: 720
      max_attempts: 2


stages:

- stage: provide_n300_fpga_images_stage
  displayName: Provide N300 FPGA Images
  dependsOn: analyze_changeset
  variables:
    UhdTestList: $[stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList']]
    BuildRequired: $[or(
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.n3xx'),
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.all')
                  )]
  jobs:
  - template: ../templates/jobs-provide-fpga-artifacts.yml
    parameters:
      id: n300
      device_name: N300
      ip_target: N300_IP
      package_name: n3xx_n300_fpga_default
      clean_ip_build: ${{ parameters.clean_ip_build }}
      num_ip_jobs: ${{ parameters.num_ip_jobs }}
      publish_int_files: ${{ parameters.publish_int_files }}
      package_and_publish_images: ${{ parameters.package_and_publish_images }}
      package_access: ${{ parameters.package_access }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      top_dir: uhddev/fpga/usrp3/top/n3xx
      target_full_matrix: ${{ parameters.n300_full_targets_matrix }}
      target_reduced_matrix: ${{ parameters.n300_reduced_targets_matrix }}

- stage: provide_n310_fpga_images_stage
  displayName: Provide N310 FPGA Images
  dependsOn: analyze_changeset
  variables:
    UhdTestList: $[stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList']]
    BuildRequired: $[or(
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.n3xx'),
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.all')
                  )]
  jobs:
  - template: ../templates/jobs-provide-fpga-artifacts.yml
    parameters:
      id: n310
      device_name: N310
      ip_target: N310_IP
      package_name: n3xx_n310_fpga_default
      clean_ip_build: ${{ parameters.clean_ip_build }}
      num_ip_jobs: ${{ parameters.num_ip_jobs }}
      publish_int_files: ${{ parameters.publish_int_files }}
      package_and_publish_images: ${{ parameters.package_and_publish_images }}
      package_access: ${{ parameters.package_access }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      top_dir: uhddev/fpga/usrp3/top/n3xx
      target_full_matrix: ${{ parameters.n310_full_targets_matrix }}
      target_reduced_matrix: ${{ parameters.n310_reduced_targets_matrix }}

- stage: provide_n320_fpga_images_stage
  displayName: Provide N320 FPGA Images
  dependsOn: analyze_changeset
  variables:
    UhdTestList: $[stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList']]
    BuildRequired: $[or(
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.n3xx'),
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.all')
                  )]
  jobs:
  - template: ../templates/jobs-provide-fpga-artifacts.yml
    parameters:
      id: n320
      device_name: N320
      ip_target: N320_IP
      package_name: n3xx_n320_fpga_default
      clean_ip_build: ${{ parameters.clean_ip_build }}
      num_ip_jobs: ${{ parameters.num_ip_jobs }}
      publish_int_files: ${{ parameters.publish_int_files }}
      package_and_publish_images: ${{ parameters.package_and_publish_images }}
      package_access: ${{ parameters.package_access }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      top_dir: uhddev/fpga/usrp3/top/n3xx
      target_full_matrix: ${{ parameters.n320_full_targets_matrix }}
      target_reduced_matrix: ${{ parameters.n320_reduced_targets_matrix }}
