parameters:
- name: testOS
  type: string
  values:
    - ubuntu2204
- name: uhdSrcDir
  type: string
- name: uhdArtifactSource
  type: string
  default: current
- name: uhdFpgaArtifactSource
  type: string
- name: fpga_imgs_source
  type: string
- name: testLength
  type: string
- name: dpdkDirs
  type: object
  default:
  - '/opt/dpdk-19.11'
  - '/opt/dpdk-23.11'

jobs:
- template: job-uhd-streaming-tests.yml
  parameters:
    suiteName: 'streamingx440'
    testOS: '${{ parameters.testOS }}'
    testLength: '${{ parameters.testLength }}'
    toolset: 'make'
    nicType: '100gbe'
    uhdSrcDir: '${{ parameters.uhdSrcDir }}'
    uhdArtifactSource: ${{ parameters.uhdArtifactSource }}
    uhdFpgaArtifactSource: ${{ parameters.uhdFpgaArtifactSource }}
    fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
    xilinxLocation: /opt/Xilinx/Vivado_Lab/2023.2
    dpdkDirs: '${{ parameters.dpdkDirs }}'
    dutMatrix:
      X440-0 CG_400:
        dutName: 'streaming-X440-0'
        dutFamily: 'x4xx'
        dutType: 'x440'
        dutAddr: '$(x440_dutAddr)'
        dutSecondAddr: '$(x440_dutSecondAddr)'
        dutFPGA: 'CG_400'
        dutNameId: ''
        dutEmbeddedImagesArtifact: 'x4xx-images'
        uartSerial: '$(x440_uartSerial)'
        dutNumRecvFrames: ''
        dutNumSendFrames: ''
        sfpInt0: '$(x440_sfpInt0)'
        sfpInt1: '$(x440_sfpInt1)'
      X440-0 CG_1600:
        dutName: 'streaming-X440-0'
        dutFamily: 'x4xx'
        dutType: 'x440'
        dutAddr: '$(x440_dutAddr)'
        dutSecondAddr: '$(x440_dutSecondAddr)'
        dutFPGA: 'CG_1600'
        dutNameId: ''
        dutEmbeddedImagesArtifact: 'x4xx-images'
        uartSerial: '$(x440_uartSerial)'
        dutNumRecvFrames: ''
        dutNumSendFrames: ''
        sfpInt0: '$(x440_sfpInt0)'
        sfpInt1: '$(x440_sfpInt1)'
