parameters:
- name: testOS
  type: string
  values:
    - ubuntu2004
- name: uhdSrcDir
  type: string

jobs:
- template: job-uhd-devtest.yml
  parameters:
    suiteName: 'rhombus'
    testOS: '${{ parameters.testOS }}'
    knownHost: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+SZhHi7YOvHW6xmVGhhZGLtqlZoPkOqGdr5WqnmLBN root@ubuntu'
    toolset: 'make'
    uhdSrcDir: '${{ parameters.uhdSrcDir }}'
    redisHost: 'sdr-rhombus'
    dutMatrix:
      rhombus-x300-UBX-0 XG:
        devType: 'x300'
        devModel: 'x300'
        devName: 'rhombus-x300-UBX-0'
        devSerial: '30A6019'
        devBus: 'ip'
        devAddr: '192.168.40.2'
        devFpga: 'XG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350A6019'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-UBX-0 XG:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-UBX-0'
        devSerial: '3138EF5'
        devBus: 'ip'
        devAddr: '192.168.40.3'
        devFpga: 'XG'
        devtestPattern: 'x3x0'
        jtagSerial: '251635138E98'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-CBX-0 XG:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-CBX-0'
        devSerial: '30796C2'
        devBus: 'ip'
        devAddr: '192.168.40.4'
        devFpga: 'XG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350796C2'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-WBX-0 XG:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-WBX-0'
        devSerial: '30C5BFF'
        devBus: 'ip'
        devAddr: '192.168.40.5'
        devFpga: 'XG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350C5BFF'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-SBX-0 XG:
        devType: 'x300'
        devModel: 'x310'
        devName: rhombus-x310-SBX-0
        devSerial: 'F43D13'
        devBus: 'ip'
        devAddr: '192.168.40.6'
        devFpga: 'XG'
        devtestPattern: 'x3x0'
        jtagSerial: '251635F43D13'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x300-UBX-0 HG:
        devType: 'x300'
        devModel: 'x300'
        devName: 'rhombus-x300-UBX-0'
        devSerial: '30A6019'
        devBus: 'ip'
        devAddr: '192.168.40.2'
        devFpga: 'HG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350A6019'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-UBX-0 HG:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-UBX-0'
        devSerial: '3138EF5'
        devBus: 'ip'
        devAddr: '192.168.40.3'
        devFpga: 'HG'
        devtestPattern: 'x3x0'
        jtagSerial: '251635138E98'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-CBX-0 HG:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-CBX-0'
        devSerial: '30796C2'
        devBus: 'ip'
        devAddr: '192.168.40.4'
        devFpga: 'HG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350796C2'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-WBX-0 HG:
        devType: 'x300'
        devModel: 'x310'
        devName: 'rhombus-x310-WBX-0'
        devSerial: '30C5BFF'
        devBus: 'ip'
        devAddr: '192.168.40.5'
        devFpga: 'HG'
        devtestPattern: 'x3x0'
        jtagSerial: '2516350C5BFF'
        jtagServer: 'nitest@sdr-rhombus'
      rhombus-x310-SBX-0 HG:
        devType: 'x300'
        devModel: 'x310'
        devName: rhombus-x310-SBX-0
        devSerial: 'F43D13'
        devBus: 'ip'
        devAddr: '192.168.40.6'
        devFpga: 'HG'
        devtestPattern: 'x3x0'
        jtagSerial: '251635F43D13'
        jtagServer: 'nitest@sdr-rhombus'
