trigger: none
schedules:
- cron: '0 13 * * 6'
  displayName: Weekly Test
  branches:
    include:
    - master
  always: true

pr: none

parameters:
- name: fpga_imgs_source
  type: string
  values:
  - 'Filesytem/Images Downloader'
  - 'FPGA Pipeline'
  - 'FPGA Pipeline PR'
  displayName: FPGA Images Source
  default: 'FPGA Pipeline'
- name: testLength
  type: string
  values:
  - 'smoke'
  - 'full'
  - 'stress'
  default: 'smoke'

variables:
  - name: uhd_fpga_artifact_source
    ${{ if eq(parameters.fpga_imgs_source,  'FPGA Pipeline PR') }}:
      value: uhd_fpga_pr_pipeline
    ${{ else }}:
      value: uhd_fpga_pipeline

resources:
  pipelines:
  - pipeline: uhd_mono_pipeline
    source: 'uhddev mono pipeline'
    branch: master
  - pipeline: usrp-kas-pipeline
    source: 'usrp-kas'
    branch: kirkstone
  - pipeline: uhd_fpga_pipeline
    source: 'uhddev fpga pipeline'
    branch: master
  - pipeline: uhd_fpga_pr_pipeline
    source: 'uhddev fpga pipeline PR'
    branch: master
  repositories:
  - repository: meta-ettus
    type: github
    name: EttusResearch/meta-ettus-dev
    endpoint: EttusResearch
    ref: kirkstone
  - repository: gr-ettus
    type: github
    name: EttusResearch/gr-ettusdev
    endpoint: EttusResearch
    ref: maint-3.8-uhd4.0
  - repository: ettus-rts
    type: github
    endpoint: EttusResearch
    name: EttusResearch/ettus-rts
    ref: master

stages:
- stage: test_uhd_devtest_stage
  displayName: Test UHD Devtest
  dependsOn: []
  jobs:
  - template: templates/tests/job-uhd-x410-hardware-tests-sdr-test0.yml
    parameters:
      testOS: 'ubuntu1804'
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
  - template: templates/tests/job-uhd-x440-hardware-tests-sdr-test0.yml
    parameters:
      testOS: 'ubuntu1804'
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
  - template: templates/job-uhd-devtest-rhombus.yml
    parameters:
      testOS: 'ubuntu2004'
      uhdSrcDir: $(Build.SourcesDirectory)
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}

- stage: test_streaming_stage
  displayName: Test UHD Streaming
  dependsOn: []
  jobs:
  - template: templates/job-uhd-streaming-tests-beauty.yml
    parameters:
      testOS: 'ubuntu2004'
      uhdSrcDir: $(Build.SourcesDirectory)/uhddev
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      testLength: ${{ parameters.testLength }}
  - template: templates/job-uhd-streaming-tests-x440.yml
    parameters:
      testOS: 'ubuntu2204'
      uhdSrcDir: $(Build.SourcesDirectory)/uhddev
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      testLength: ${{ parameters.testLength }}

- stage: test_rf_tests_stage
  displayName: Test UHD RF Tests
  dependsOn: []
  jobs:
  - template: templates/job-uhd-rf-tests-pebbles.yml
    parameters:
      testOS: 'ubuntu1804'
      uhdSrcDir: $(Build.SourcesDirectory)/uhddev
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
  - template: templates/tests/job-uhd-x410-hardware-tests-pebbles.yml
    parameters:
      testOS: 'ubuntu1804'
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      testLength: ${{ parameters.testLength }}
  - template: templates/tests/job-uhd-x440-hardware-tests-pebbles.yml
    parameters:
      testOS: 'ubuntu1804'
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      testLength: ${{ parameters.testLength }}

- stage: test_uhd_phase_tests
  displayName: Test UHD Phase Tests
  dependsOn: []
  jobs:
  - template: templates/tests/job-uhd-x440-hardware-tests-saison.yml
    parameters:
      testOS: 'ubuntu2204'
      uhdArtifactSource: uhd_mono_pipeline
      uhdFpgaArtifactSource: ${{ variables.uhd_fpga_artifact_source }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      testLength: ${{ parameters.testLength }}
      extra_rf_test_args: --test_selector test_rx_phase_coherence.py test_tx_phase_coherence.py
