#!/bin/sh

sudo /usr/bin/fix-buildkite-agent-ccache-permissions
sudo /usr/bin/fix-buildkite-agent-builds-permissions \
	"${BUILDKITE_AGENT_NAME}" \
	"${BUILDKITE_ORGANIZATION_SLUG}" \
	"${BUILDKITE_PIPELINE_NAME}"
